"""The Consultant: scans a project's dependency manifests and writes a context file
(CLAUDE.md by default) listing the active and deprecated practices that apply to its stack.

    detect_stack -> query_graph -> generate_markdown -> write_files
"""

import json
import logging
import re
import tomllib
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field

from .models import NodeStatus
from .store import KnowledgeStore

logger = logging.getLogger(__name__)

STACK_MATCH_THRESHOLD = 0.65

TEMPLATE = """# Project Context: {project_name}
<!-- Generated by GraphAgentDB. Run `graphagentdb bootstrap` to refresh. -->

Developer guidelines for **{project_name}**, compiled from the GraphAgentDB knowledge graph:
the practices that apply to this stack, and the patterns that have been superseded.

---

## Detected Technology Stack
{stack_list}

---

## Active Principles & Guidelines
{guidelines_section}

---

## Deprecated & Superseded Patterns (DO NOT USE)
{deprecated_section}

---

## Meta
*   **Generated**: {timestamp}
*   **Active rules compiled**: {node_count}
"""


class ConsultState(BaseModel):
    project_path: str = "."
    stack_keys: list[str] = Field(default_factory=list)
    active_nodes: list[dict[str, Any]] = Field(default_factory=list)
    markdown_output: str = ""
    written_paths: list[str] = Field(default_factory=list)
    status: str = "pending"
    error: str | None = None


def _requirement_name(spec: str) -> str:
    return re.split(r"[\s\[<>=!~;@]", spec.strip(), maxsplit=1)[0].lower()


def detect_stack(project_dir: Path) -> list[str]:
    """Collects dependency names from package.json, pyproject.toml, requirements.txt and Cargo.toml."""
    stack: set[str] = set()

    pkg = project_dir / "package.json"
    if pkg.exists():
        try:
            data = json.loads(pkg.read_text(encoding="utf-8"))
            deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
            stack |= {name.lower().lstrip("@").split("/")[-1] for name in deps}
        except (json.JSONDecodeError, OSError):
            logger.warning("Could not parse %s", pkg)

    pyproject = project_dir / "pyproject.toml"
    if pyproject.exists():
        try:
            data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
            project = data.get("project", {})
            specs = list(project.get("dependencies", []))
            for extra in project.get("optional-dependencies", {}).values():
                specs += extra
            stack |= {_requirement_name(s) for s in specs if s.strip()}
        except (tomllib.TOMLDecodeError, OSError):
            logger.warning("Could not parse %s", pyproject)

    requirements = project_dir / "requirements.txt"
    if requirements.exists():
        for line in requirements.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith(("#", "-")):
                stack.add(_requirement_name(line))

    cargo = project_dir / "Cargo.toml"
    if cargo.exists():
        try:
            data = tomllib.loads(cargo.read_text(encoding="utf-8"))
            for section in ("dependencies", "dev-dependencies"):
                stack |= {name.lower() for name in data.get(section, {})}
        except (tomllib.TOMLDecodeError, OSError):
            logger.warning("Could not parse %s", cargo)

    stack.discard("")
    return sorted(stack)


def format_guidelines(nodes: list[dict[str, Any]]) -> str:
    if not nodes:
        return "_No active principles found for the detected stack._"
    lines = []
    for n in nodes:
        lines += [
            f"### {n['name']} (`{n['type'].upper()}`)",
            f"> ID: `{n['id']}`",
            "",
            n["description"],
            "",
        ]
    return "\n".join(lines)


def format_deprecated(nodes: list[dict[str, Any]]) -> str:
    deprecated = [n for n in nodes if n["status"] == NodeStatus.DEPRECATED.value]
    if not deprecated:
        return "_No deprecated patterns documented._"
    lines = []
    for n in deprecated:
        lines += [
            f"*   **{n['name']}** (ID: `{n['id']}`): *DEPRECATED*",
            f"    *   *Superseded by*: `{n.get('superseded_by') or 'N/A'}`",
            f"    *   *Reason*: {n.get('supersession_reason') or 'Updated paradigm.'}",
        ]
    return "\n".join(lines)


def build_consultant(store: KnowledgeStore):
    """Compiles the bootstrap workflow bound to a store."""
    settings = store.settings

    def detect_stack_node(state: ConsultState) -> dict:
        path = Path(state.project_path)
        if not path.is_dir():
            return {"error": f"Project path does not exist: {state.project_path}"}
        keys = detect_stack(path)
        logger.info("Detected stack: %s", keys)
        return {"stack_keys": keys}

    def query_graph(state: ConsultState) -> dict:
        if state.error:
            return {}
        all_nodes = store.get_all_nodes()
        if not state.stack_keys:
            return {
                "active_nodes": [n for n in all_nodes if n["status"] == NodeStatus.ACTIVE.value]
            }

        matched: set[str] = set()
        for key in state.stack_keys:
            matched |= {
                hit["node_id"]
                for hit in store.semantic_search(key, top_k=2)
                if hit["score"] > STACK_MATCH_THRESHOLD
            }
        if not matched:
            # Fall back to plain substring matching on names and descriptions.
            for node in all_nodes:
                haystack = f"{node['name']} {node['description']}".lower()
                if node["status"] == NodeStatus.ACTIVE.value and any(
                    key in haystack for key in state.stack_keys
                ):
                    matched.add(node["id"])

        subgraph = store.get_subgraph(sorted(matched), max_depth=2)
        active = [n for n in subgraph["nodes"] if n["status"] == NodeStatus.ACTIVE.value]
        logger.info("Retrieved %d active concepts", len(active))
        return {"active_nodes": active}

    def generate_markdown(state: ConsultState) -> dict:
        if state.error:
            return {}
        stack_list = (
            "\n".join(f"*   `{k}`" for k in state.stack_keys)
            if state.stack_keys
            else "_No dependency manifests detected._"
        )
        markdown = TEMPLATE.format(
            project_name=Path(state.project_path).resolve().name or "Workspace",
            stack_list=stack_list,
            guidelines_section=format_guidelines(state.active_nodes),
            deprecated_section=format_deprecated(store.get_all_nodes()),
            timestamp=datetime.now(UTC).isoformat(timespec="seconds"),
            node_count=len(state.active_nodes),
        )
        return {"markdown_output": markdown}

    def write_files(state: ConsultState) -> dict:
        if state.error or not state.markdown_output:
            return {}
        project = Path(state.project_path)
        target = project / settings.context_filename
        try:
            target.write_text(state.markdown_output, encoding="utf-8")
        except OSError as exc:
            return {"error": f"Failed to write {target}: {exc}"}
        written = [str(target)]

        try:
            settings.exports_dir.mkdir(parents=True, exist_ok=True)
            backup = settings.exports_dir / f"{project.resolve().name}.md"
            backup.write_text(state.markdown_output, encoding="utf-8")
            written.append(str(backup))
        except OSError:
            logger.warning("Could not write backup copy", exc_info=True)

        return {"written_paths": written, "status": "success"}

    workflow = StateGraph(ConsultState)
    workflow.add_node("detect_stack", detect_stack_node)
    workflow.add_node("query_graph", query_graph)
    workflow.add_node("generate_markdown", generate_markdown)
    workflow.add_node("write_files", write_files)
    workflow.set_entry_point("detect_stack")
    workflow.add_edge("detect_stack", "query_graph")
    workflow.add_edge("query_graph", "generate_markdown")
    workflow.add_edge("generate_markdown", "write_files")
    workflow.add_edge("write_files", END)
    return workflow.compile()


def bootstrap(store: KnowledgeStore, project_path: str) -> ConsultState:
    """Runs the bootstrap workflow and returns the final state."""
    result = build_consultant(store).invoke(ConsultState(project_path=project_path))
    return ConsultState.model_validate(result)
